# -*- coding: utf-8 -*-
"""Text Summarization using LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZd9r7hR2rjFn51qW8QGnl86-A1rrzC9
"""

from transformers import T5Tokenizer, T5ForConditionalGeneration

# load pre-trained T5 model and tokenizer
model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

text = """
The COVID-19 pandemic has brought unprecedented challenges to the global economy...
"""
# prepare the text for the T5 model by adding the "summarize:" prefix
input_text = "summarize: " + text

# tokenize the input text
input_ids = tokenizer.encode(input_text,
                             return_tensors="pt",
                             max_length=512,
                             truncation=True)

summary_ids = model.generate(
    input_ids,
    max_length=50,   # maximum length of the summary
    num_beams=4,     # beam search for better results
    length_penalty=2.0,  # length penalty to avoid lengthy summaries
    early_stopping=True
)

# decode the summary
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Summary:", summary)